### ISSUE TITLE
no command executed and nothing in verbose

### ISSUE THREAD

**Issue by 2Belette** [a-sk/python-imapnotify#1]
Hi, 

I am trying your script and I don't understand the issue, probably the way I am building the config but as I didn't find any example nor any documentation I tried multiple things:

`{"host": "outlook.office365.com", "port": "993", "username": "xxx@xxx.com", "password": "xxxxxx", "boxes": ["INBOX": {"on_new_message": "echo hey"}]}`

or

`{"host": "outlook.office365.com", "port": "993", "username": "xxx@xxx.com", "password": "xxxxxx", "on_new_message": "echo hey", "boxes": ["INBOX"]}`

or

`{"host": "outlook.office365.com", "port": "993", "username": "xxx@xxx.com", "password": "xxxxxx", "onNewMail": "echo hey", "boxes": ["INBOX"]}`

Any tips?

Analyzing the traffic between the server and my pc, I can definitely see the IDLE message coming but it triggers nothing on your script, nothing in the verbose log as well.

Many thanks :)

**Comment by protist** [comment]
I've been using python-imapnotify for a while, but I've just noticed that it's failing for me too now. I'm using Arch Linux, so it might have been an update to some dependency.
```
$ pyimapnotify -c /path/to/config.json -vvv
2017-10-28 20:04:01,529 DEBUG [core:90] adding INBOX
2017-10-28 20:04:01,529 INFO [core:76] connecting to foo.com:993 for INBOX
2017-10-28 20:04:02,420 INFO [core:82] connected to foo.com:993 for INBOX
2017-10-28 20:04:02,420 DEBUG [core:86] [INBOX] connected
2017-10-28 20:04:02,497 DEBUG [core:130] [INBOX] set idle mode
2017-10-28 20:04:02,571 DEBUG [core:118] [INBOX] new data: ['+ idling']
2017-10-28 20:04:56,008 DEBUG [core:118] [INBOX] new data: ['22 EXISTS', '1 RECENT']
```
The last line appears after the new mail arrives, so it looks like imapnotify is seeing the new mail. However, nothing is triggered. (I'm not sure if this is the same error as @2Belette; I'm happy to open a new issue if it is different.)

**Comment by 2Belette** [comment]
@protist I think it is definitely the same issue we have together!

Would you mind to share your (anonymised) config ?

**Comment by protist** [comment]
Sure! This was working at some point, but now fails.
```
{
   "host": "foo.com",
   "port": 993,
   "tls": true,
   "socketTimeout": 10000,
   "tlsOptions": { "rejectUnauthorized": true },
   "username": "bar@foo.com",
   "password_eval": "python -m keyring get mbsync bar@foo.com",
   "onNewMail": "/usr/bin/touch /tmp/works",
   "onNewMailPost": "",
   "boxes":
     [
       "INBOX"
     ]
}
```

**Comment by protist** [comment]
OTOH I re-tested the latest version of node-imapnotify, and that seems to be working very well now!

**Comment by 2Belette** [comment]
@protist thanks for the tips, node-imapnotify is effectively working !
Only one (important) thing for me is that I am unable to make it work with [pass](https://www.passwordstore.org/), I see you are using a keyring as well on your side.

` "password_eval": "/usr/bin/pass servers/email",`

is failling for me :
```
{"name":"imap_inotify","hostname":"x","pid":27719,"level":50,"box":"INBOX","msg":"Error registered","time":"2017-10-30T12:31:52.486Z","v":0}
{"name":"imap_inotify","hostname":"x","pid":27719,"level":50,"box":"INBOX","msg":"{ Error: No supported authentication method(s) available. Unable to login.\n    at Connection.<anonymous> (/usr/lib/node_modules/imapnotify/node_modules/imap/lib/Connection.js:1679:15)\n    at Connection._resTagged (/usr/lib/node_modules/imapnotify/node_modules/imap/lib/Connection.js:1535:22)\n    at Parser.<anonymous> (/usr/lib/node_modules/imapnotify/node_modules/imap/lib/Connection.js:194:10)\n    at emitOne (events.js:96:13)\n    at Parser.emit (events.js:191:7)\n    at Parser._resTagged (/usr/lib/node_modules/imapnotify/node_modules/imap/lib/Parser.js:175:10)\n    at Parser._parse (/usr/lib/node_modules/imapnotify/node_modules/imap/lib/Parser.js:139:16)\n    at Parser._tryread (/usr/lib/node_modules/imapnotify/node_modules/imap/lib/Parser.js:82:15)\n    at TLSSocket.Parser._cbReadable (/usr/lib/node_modules/imapnotify/node_modules/imap/lib/Parser.js:53:12)\n    at emitNone (events.js:86:13) source: 'authentication' }","time":"2017-10-30T12:31:52.487Z","v":0}
```

**Comment by protist** [comment]
No worries; glad to help!

I don't use pass, but it should matter. It looks like the output of the quoted command is directly fed into imapnotify, minus the final newline. So you can test the command alone, then test substituting the output.

In my case, I directly run the following on the command line

    $ python -m keyring get mbsync bar@foo.com

Which outputs my password + newline. Is that the same for

    $ /usr/bin/pass servers/email

? If so, then you can further test putting the password into the config file directly as plaintext.

**Comment by 2Belette** [comment]
yep, exactly the same like you, but it is like it doesn't issue the command at all on my side.
putting the password in the cleartext is working.

I am using this pass command as well on my mbsync and msmtp without any issue

**Comment by protist** [comment]
Honestly, I can't think why this might be the case. I guess you can try and reduce as many differences with my working config as you can. Is the rest of your config identical to mine (except for user stuff of course)?

Otherwise (and I have no idea why this might be), you could try changing the command to make it more like mine, e.g. not using the full path to the executable, and removing the `/` from the argument. Or try python keyring, just to see if it works.

**Comment by 2Belette** [comment]
yep, I got the exact same configuration like yours, the only diff is the usage of pass.
I am opening an issue to node-imapnotify as the issue is with it and here we have no answer yet on the reason why the python-imapnotify is not working...

**Comment by serycjon** [comment]
Just encountered the same issue and found a fix:
rewrite core.py:_is_new_msg() to:

    def _is_new_msg(self, msg):
      for x in msg:
        if 'EXISTS' in x:
          return True

Do not understand what is going on and if it is specific to my python version (3.7.4)
